### ISSUE TITLE
Atlas Operator should Integrate with 3rd party Secrets Management

### ISSUE THREAD

**Issue by alex-tw-lam** [mongodb/mongodb-atlas-kubernetes#247]
Kubernetes secrets are known to be insecure, they are mere base64 of plaintext. 

The operator should integrate with some mainstream secret management solutions, such as AWS secret manager, Azure KV and Hashicorp Vault. 

This would enable the operator to meet some of the more stringent compliance requirements and integrate with corporate environments.

Alex

**Comment by denist-huma** [comment]
:+1: Secret Manager | Google Cloud

**Comment by jasonmimick** [comment]
Hi-
Integration with HashiCorp Vault is in the product roadmap for the MongoDB Atlas Kubernetes Operator.
However, since there is already an existing direct integration between MongoDB Atlas and Vault which is somewhat orthogonal to the `AtlasDatabaseUser` custom resource control vector, but can be integrated into your Kubernetes deployments today. In this kind of deployment, one would manage all the MongoDB Database users directly through Vault and not the Kubernetes custom resources.

To find out more about this integration, pls visit: https://www.mongodb.com/atlas/hashicorp-vault
